# root -l -q -b "doOrthogonalMethod.C(\"data\",\"MET\")"
# root -l -q -b "doOrthogonalMethod.C(\"mc\",\"MET\")"
# root -l -q -b "doOrthogonalMethod.C(\"data\",\"pt1\")"
# root -l -q -b "doOrthogonalMethod.C(\"mc\",\"pt1\")"
# root -l -q -b "doOrthogonalMethod.C(\"data\",\"pt2\")"
# root -l -q -b "doOrthogonalMethod.C(\"mc\",\"pt2\")"
# root -l -q -b "doOrthogonalMethod.C(\"data\",\"eta1\")"
# root -l -q -b "doOrthogonalMethod.C(\"mc\",\"eta1\")"
# root -l -q -b "doOrthogonalMethod.C(\"data\",\"eta2\")"
# root -l -q -b "doOrthogonalMethod.C(\"mc\",\"eta2\")"
# root -l -q -b "doOrthogonalMethod.C(\"data\",\"drll\")"
# root -l -q -b "doOrthogonalMethod.C(\"mc\",\"drll\")"


root -l -q -b "getEff_and_plot.C(\"MET\")"
root -l -q -b "getEff_and_plot.C(\"pt1\")"
root -l -q -b "getEff_and_plot.C(\"pt2\")"
root -l -q -b "getEff_and_plot.C(\"eta1\")"
root -l -q -b "getEff_and_plot.C(\"eta2\")"
root -l -q -b "getEff_and_plot.C(\"drll\")"